config/_default/menus.toml
layouts/partials/footer.html

- Sync menus with main site
- Sync footer with main site

Sync with main site.

---

README.md

Update blog link.

---

config/_default/menus.toml
layouts/partials/footer.html

- Update navbar, Add resources section
- Update footer social buttons

Navbar and footer fixes

---

archetypes/default.md

Fixes incorrect blog archetype.

Fix blog template date

---

content/blog/project-kickstart-checklist.md

Added a few more lines

---

content/blog/project-kickstart-checklist.md

Project kickoff cl

---

content/blog/tdd-assessment.md

We have been seeing some of the repos with very few/redundant commit messages, this is a potential fix.

Explicit message for git commits

---

config/_default/params.toml
layouts/partials/style.html

Makes all the titles *h1 ... h6* Capital Case

Capitalize titles

---

layouts/partials/style.html

Fix footer top margin

---

content/authors/abhishek-keshri/_index.md
content/authors/jaymin-shah/_index.md
content/authors/karishma-shah/_index.md
content/authors/utsav-parmar/_index.md

Adding these profiles covers all the authors for all our articles (excluding people who have left in the past)

Add author profiles

---

content/blog/technical-assessment-evaluation-criteria.md

Software Craft round and XP part needs more work

Updated new interview process

---

content/authors/sapan-parikh/_index.md

Changes Sapan's bio

---

content/blog/five-git-tricks.md

Co-authored-by: Abhsihek Keshri <iam2kabhishek@gmail.com>

Hardcode links to sections

---

layouts/partials/style.html

Fixes image aspect ratios, #77

---

layouts/_default/single.html
layouts/partials/share-buttons.html

- https://sharingbuttons.io/
SEO enhancement

Share buttons below blogs

---

config/_default/menus.toml

Syncs the services section with main site

Update navbar and footer links for services

---

content/blog/sh-case-study.md

SH Globalization Case Study

---

content/blog/sh-case-study.md

Removes SH reference

---

content/blog/a-developers-daily-checklist.md

Make wording more exclusive

---

.github/workflows/gh-pages.yml
content/blog/global-case-study.md

`hugo --minify` was causing problems with multiple authors, this PR removes it
- build: remove minify to allow multiple authors
- blog: update global case study authors 🤝

Build: Allow Multiple Authors

---

content/blog/monnai-case-study.md

Added a section that mentions about funding

Blog: Update: Monnai Case Study - added section for funding

---

layouts/partials/global-case-study.html

Update case study with content-only changes

---

config/_default/config.toml
content/blog/learnings-from-clean-coder.md
layouts/_default/list.html
layouts/_default/single.html
layouts/partials/style.html

Add authors on cards

---

layouts/partials/header.html
layouts/partials/style.html

added dark mode for desktop and tablet.
need some additional work for mobile as there is not enough space in the header for all buttons as is.

dark mode re-added

---

content/blog/psychological-safety.md

Added link and updated tags in psychological-safety.md

---

content/blog/testing-with-java-2-tdd.md

- Change x to y
- Update foo logic
- Item was missing
- Item needed changes
Please include any relevant screenshots that may help explain the change.

FIX: Fixed image tag

---

layouts/partials/finance-case-study.html
layouts/partials/global-case-study.html
layouts/partials/monnai-case-study.html

- Fixed testimonial Section
- Section spacing and alignment wasn't proper
Please include any relevant screenshots that may help explain the change.

fix: testimonial section

---

content/blog/codescene-refactoring.md

"one can always find small tidying activities" to "one can always find small tidying opportunities"

Fix: Text change in codescene-refactoring.md

---

content/blog/four-lenses-of-productivity.md
content/blog/four-lenses-of-productivity/ind-team-org-market.json
layouts/shortcodes/circlepack.html

Four lenses of productivity

---

layouts/shortcodes/circlepack.html

- Change x to y
- Update foo logic
- Item was missing
- Item needed changes
Please include any relevant screenshots that may help explain the change.

changes the URL of JSON to make the graph work on the prod blog

---

content/blog/four-lenses-of-productivity.md
content/blog/four-lenses-of-productivity/ind-team-org-market.json

Updated content of blog - four lenses of productivity

---

content/blog/acclerate-metrics.md

Changed title as per feedback

---

content/blog/chandrayaan-3-tdd-assessment.md

- Change x to y
- Update foo logic
- Item was missing
- Item needed changes
Please include any relevant screenshots that may help explain the change.

Update Final direction in the example for Chandrayaan 3 TDD assessment

---

content/blog/build-deployment-case-study.md

Updated cards description in modernization case study

---

content/blog/monkey-patch.md

Updated content in monkey-patch.md

---

config/_default/languages.toml

- ci: add prettier github action
- ci: add dry option
- ci: do not run gh page build on non main
- feat: update markdown formatting rules
- fix: content formatting
- fix: data engineer formatting
- fix: standup formatting
- chore: update theme submodule
- feat: update copyright year

Update Bigspring Theme and Copyright Year

---

static/search.js

- [] Added this
- [x ] Updated that
- Previously we simple redirect to tag
- But we have to redirect to urlize tag 

FIX: Modifies the redirection URL

---

layouts/partials/lets-talk.html

fix broken url for let's talk button
Because it was broken
Because it was broken

broken url for let's talk button

---

layouts/partials/subscribe.html

Better subscribe message

---

content/blog/the-tale-of-tdd.md

Added "TDD" to the tag of Tale of TDD blog

---

content/blog/role-of-pr-reviews.md

Fixed spacing issues in new blog

---

.github/workflows/gh-pages.yml
README.md
config/_default/config.toml
config/_default/params.toml
content/blog/a-developers-daily-checklist.md
content/blog/five-git-tricks.md
content/blog/tech-debt.md
content/blog/technical-assessment-evaluation-criteria.md
content/blog/testing-with-java-1-intro.md
content/blog/testing-with-java-2-tdd.md

- **Revert "Merge pull request #215 from incubyte/move-blog"**
- **Revert "ci: change blog cname"**

Revert domain move

---

layouts/_default/list.html
layouts/partials/header.html
layouts/partials/style.html

Fix small screen issues

---

.github/workflows/gh-pages.yml
README.md
config/_default/config.toml
config/_default/params.toml
content/blog/a-developers-daily-checklist.md
content/blog/five-git-tricks.md
content/blog/tech-debt.md
content/blog/technical-assessment-evaluation-criteria.md
content/blog/testing-with-java-1-intro.md
content/blog/testing-with-java-2-tdd.md

This reverts commit 29d8c8e379a8ffdec961b476167e72d2281b4126, reversing
changes made to 6b399b2d8e8729fd571c717430a6f91bf3c35506.

Move domain to engineering.incubyte.co

---

.github/workflows/gh-pages.yml
README.md
config/_default/config.toml
config/_default/params.toml
content/blog/a-developers-daily-checklist.md
content/blog/five-git-tricks.md
content/blog/tech-debt.md
content/blog/technical-assessment-evaluation-criteria.md
content/blog/testing-with-java-1-intro.md
content/blog/testing-with-java-2-tdd.md

- **Revert "Merge pull request #224 from incubyte/revert-domain"**
- **ci: move to engineering**

ci: move domain to engineering

---

.github/workflows/gh-pages.yml
README.md
config/_default/config.toml
config/_default/params.toml
content/blog/a-developers-daily-checklist.md
content/blog/five-git-tricks.md
content/blog/tech-debt.md
content/blog/technical-assessment-evaluation-criteria.md
content/blog/testing-with-java-1-intro.md
content/blog/testing-with-java-2-tdd.md

This reverts commit feb8900546c93b210bfaeca437f712328df36f07, reversing
changes made to 1c81db2f823eb22eebfc90b198f4788442fb9fca.

Move back to blog.incubyte.co

---

content/blog/chandrayaan-3-tdd-assessment.md
content/blog/clean-agile-with-uncle-bob-a-summary.md
content/blog/code-coverage.md
content/blog/learnings-from-clean-coder.md
content/blog/learnings-from-terraform.md

- Font sizes of sub-headers affected the overall design of the blog page

Fixed the header font sizes of several blogs 

---

content/blog/write-cleaner-rails-code-with-fear.md
static/images/2024/write-cleaner-rails-code-with-fear/header.svg

- I added a new blog to explain a gem that can neglect nil checks and begin/rescue from the entire rails application.
- I want to share about the Fear gem I frequently use in my pet projects.

Add new blog - Write clean rails code with fear

---

content/blog/dynamic-method.md

Use consistent indentation for code in ruby dynamic methods blog
Consistent indentation of the code

Using consistent indentation for code

---

content/blog/vitest-react-testing-library-guide.md
static/images/2025/vitest-react-testing-library-guide/header.svg

Blog: Vitest with React Testing Library, A Modern Approach to Testing React Apps

---

content/blog/we-let-ai-code-for-us-prompts-were-prayers-and-code-was-interesting.md

Creating a new PR for addressing changes suggested on AI hackathon learnings blog

Addressing suggested changes

---

config/_default/config.toml

Noticed that yesterday when I was reading @heetvadiya's blog.

Update copyright year in config.toml to 2025

---

content/blog/we-let-ai-code-for-us-prompts-were-prayers-and-code-was-interesting.md

- change mid-air to enroute
- add observation regarding same template of lovable for landing pages

Address changes suggested by general

---

content/blog/tdd-assessment.md

- Prettier fix which is causing all PR github action to fail

Prettier fix
